export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const GET_TOTAL_PRODUCTS_REQUEST = "GET_TOTAL_PRODUCTS_REQUEST";
export const GET_TOTAL_PRODUCTS_SUCCESS = "GET_TOTAL_PRODUCTS_SUCCESS";
export const GET_TOTAL_PRODUCTS_FAIL = "GET_TOTAL_PRODUCTS_FAIL";

export const GET_NEW_ARRIVALS_REQUEST = "GET_NEW_ARRIVALS_REQUEST";
export const GET_NEW_ARRIVALS_SUCCESS = "GET_NEW_ARRIVALS_SUCCESS";
export const GET_NEW_ARRIVALS_FAIL = "GET_NEW_ARRIVALS_FAIL";

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

export const LIST_PRODUCTS_REQUEST = "LIST_PRODUCTS_REQUEST";
export const LIST_PRODUCTS_SUCCESS = "LIST_PRODUCTS_SUCCESS";
export const LIST_PRODUCTS_FAIL = "LIST_PRODUCTS_FAIL";

export const LIST_RELATED_PRODUCTS_REQUEST = "LIST_RELATED_PRODUCTS_REQUEST";
export const LIST_RELATED_PRODUCTS_SUCCESS = "LIST_RELATED_PRODUCTS_SUCCESS";
export const LIST_RELATED_PRODUCTS_FAIL = "LIST_RELATED_PRODUCTS_FAIL";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const GET_PRODUCT_RESET = "GET_PRODUCT_RESET";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const RATE_PRODUCT_REQUEST = "RATE_PRODUCT_REQUEST";
export const RATE_PRODUCT_SUCCESS = "RATE_PRODUCT_SUCCESS";
export const RATE_PRODUCT_FAIL = "RATE_PRODUCT_FAIL";
export const RATE_PRODUCT_RESET = "RATE_PRODUCT_RESET";
