export const SEARCH_QUERY = "SEARCH_QUERY";

export const GET_SEARCH_REQUEST = "GET_SEARCH_REQUEST";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAIL = "GET_SEARCH_FAIL";
export const GET_SEARCH_RESET = "GET_SEARCH_RESET";
