export const CREATE_SUB_CATEGORY_REQUEST = "CREATE_SUB_CATEGORY_REQUEST";
export const CREATE_SUB_CATEGORY_SUCCESS = "CREATE_SUB_CATEGORY_SUCCESS";
export const CREATE_SUB_CATEGORY_FAIL = "CREATE_SUB_CATEGORY_FAIL";
export const CREATE_SUB_CATEGORY_RESET = "CREATE_SUB_CATEGORY_RESET";

export const GET_ALL_SUB_CATEGORIES_REQUEST = "GET_ALL_SUB_CATEGORIES_REQUEST";
export const GET_ALL_SUB_CATEGORIES_SUCCESS = "GET_ALL_SUB_CATEGORIES_SUCCESS";
export const GET_ALL_SUB_CATEGORIES_FAIL = "GET_ALL_SUB_CATEGORIES_FAIL";

export const GET_SUB_CATEGORY_BY_ID_REQUEST = "GET_SUB_CATEGORY_BY_ID_REQUEST";
export const GET_SUB_CATEGORY_BY_ID_SUCCESS = "GET_SUB_CATEGORY_BY_ID_SUCCESS";
export const GET_SUB_CATEGORY_BY_ID_FAIL = "GET_SUB_CATEGORY_BY_ID_FAIL";

export const DELETE_SUB_CATEGORY_REQUEST = "DELETE_SUB_CATEGORY_REQUEST";
export const DELETE_SUB_CATEGORY_SUCCESS = "DELETE_SUB_CATEGORY_SUCCESS";
export const DELETE_SUB_CATEGORY_FAIL = "DELETE_SUB_CATEGORY_FAIL";
export const DELETE_SUB_CATEGORY_RESET = "DELETE_SUB_CATEGORY_RESET";

export const UPDATE_SUB_CATEGORY_REQUEST = "UPDATE_SUB_CATEGORY_REQUEST";
export const UPDATE_SUB_CATEGORY_SUCCESS = "UPDATE_SUB_CATEGORY_SUCCESS";
export const UPDATE_SUB_CATEGORY_FAIL = "UPDATE_SUB_CATEGORY_FAIL";
