export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const CREATE_OR_UPDATE_USER_REQUEST = "CREATE_OR_UPDATE_USER_REQUEST";
export const CREATE_OR_UPDATE_USER_SUCCESS = "CREATE_OR_UPDATE_USER_SUCCESS";
export const CREATE_OR_UPDATE_USER_FAIL = "CREATE_OR_UPDATE_USER_FAIL";

export const GET_CURRENT_USER_REQUEST = "GET_CURRENT_USER_REQUEST";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";
export const GET_CURRENT_USER_RESET = "GET_CURRENT_USER_RESET";

export const GET_CURRENT_ADMIN_USER_REQUEST = "GET_CURRENT_ADMIN_USER_REQUEST";
export const GET_CURRENT_ADMIN_USER_SUCCESS = "GET_CURRENT_ADMIN_USER_SUCCESS";
export const GET_CURRENT_ADMIN_USER_FAIL = "GET_CURRENT_ADMIN_USER_FAIL";
export const GET_CURRENT_ADMIN_USER_RESET = "GET_CURRENT_ADMIN_USER_RESET";

export const USER_LOGOUT = "USER_LOGOUT";
